config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :locations
  resources :students
  resources :families

  resources :users, only: [:create, :destroy]
  resources :sessions

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  get 'login', to: 'home#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # get '*a', to: 'errors#routing'

  get 'camp_report/:id', to: 'camps#report', as: :camp_report
  get 'family_report/:id/', to: 'families#report', as: :family_report
  get 'family_report/:id/:year', to: 'families#yearly_report', as: :family_yearly_report

  get 'annual_report/:year/', to: 'home#annual_report', as: :annual_report
end

app/models/camp.rb
class Camp < ActiveRecord::Base
  include ChessCampHelpers

  # relationships
  belongs_to :curriculum
  has_many :camp_instructors
  has_many :instructors, through: :camp_instructors
  belongs_to :location
  has_many :registrations
  has_many :students, through: :registrations

  # validations
  validates_presence_of :curriculum_id, :time_slot, :start_date
  validates_numericality_of :cost, only_integer: true, greater_than_or_equal_to: 0
  validates_date :start_date, on_or_after: lambda { Date.today }, on_or_after_message: "cannot be in the past", on:  :create
  validates_date :end_date, on_or_after: :start_date
  validates_inclusion_of :time_slot, in: %w[am pm], message: "is not an accepted time slot"
  validates_numericality_of :max_students, only_integer: true, greater_than: 0, allow_blank: true
  validate :curriculum_is_active_in_the_system
  validate :location_is_active_in_the_system
  validate :camp_is_not_a_duplicate, on: :create
  validate :max_students_not_greater_than_capacity
  validate :camp_can_be_deactivated

  # scopes
  scope :alphabetical, -> { joins(:curriculum).order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :chronological, -> { order('start_date','end_date') }
  scope :morning, -> { where('time_slot = ?','am') }
  scope :afternoon, -> { where('time_slot = ?','pm') }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }
  scope :past, -> { where('end_date < ?', Date.today) }
  scope :for_curriculum, ->(curriculum_id) { where("curriculum_id = ?", curriculum_id) }
 

  # instance methods
  def name
    self.curriculum.name
  end

  def already_exists?
    Camp.where(time_slot: self.time_slot, start_date: self.start_date, location_id: self.location_id).size == 1
  end

  # class methods
  def self.openings
    Camp.active.chronological.to_a.select{|c| c.registrations.size < c.max_students}
  end

  # callbacks
  before_destroy :verify_that_there_are_no_registrations_for_camp
  before_update :remove_instructors_from_inactive_camp

  # private
  def curriculum_is_active_in_the_system
    is_active_in_system(:curriculum)
  end

  def location_is_active_in_the_system
    is_active_in_system(:location)
  end

  def camp_is_not_a_duplicate
    return true if self.time_slot.nil? || self.start_date.nil? || self.location_id.nil?
    if self.already_exists?
      errors.add(:time_slot, "already exists for start date, time slot and location")
    end
  end

  def verify_that_there_are_no_registrations_for_camp
    self.registrations.to_a.empty?
  end

  def camp_can_be_deactivated
    return true if self.active
    unless verify_that_there_are_no_registrations_for_camp
      errors.add(:base, "Camp cannot be inactive because there are students registered")
      return false
    end
    return true
  end

  def max_students_not_greater_than_capacity
    return true if self.max_students.nil? || self.location_id.nil?
    if self.max_students > self.location.max_capacity
      errors.add(:max_students, "is greater than the location capacity")
    end
  end

  def remove_instructors_from_inactive_camp
    # confirm that no registrations for camp and camp is marked as inactive
    if verify_that_there_are_no_registrations_for_camp && !self.active
      self.camp_instructors.each{|ci| ci.destroy}
    end
  end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  authorize_resource
  skip_authorize_resource only: [:index, :show]
  before_action :set_camp, only: [:show, :edit, :update, :destroy, :report]

  def index
    @upcoming_camps = Camp.upcoming.active.chronological.paginate(page: params[:page]).per_page(10)
    @past_camps = Camp.past.chronological.paginate(page: params[:page]).per_page(10)
    @inactive_camps = Camp.inactive.alphabetical.to_a
  end

  def show
    @instructors = @camp.instructors.alphabetical.to_a
    @curriculum = @camp.curriculum
    @location = @camp.location
    @registered_students = @camp.students.alphabetical
    @registrations = @camp.registrations
  end

  def new
    @camp = Camp.new
  end

  def edit
    @camp = Camp.find(params[:id])
    @camp.start_date = humanize_date @camp.start_date
    @camp.end_date = humanize_date @camp.end_date
  end

  def create
    temp_camp_params = camp_params
    temp_camp_params[:start_date] = Chronic.parse(camp_params[:start_date])
    temp_camp_params[:end_date] = Chronic.parse(camp_params[:end_date])
   
    @camp = Camp.new(temp_camp_params)

    if @camp.save
      redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    temp_camp_params = camp_params
    temp_camp_params[:start_date] = Chronic.parse(camp_params[:start_date])
    temp_camp_params[:end_date] = Chronic.parse(camp_params[:end_date])

    begin
      @camp.update(temp_camp_params)
      redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was revised in the system."
      
    rescue Exception => e
        flash[:error] = "This camp, or its instructor assignments are invalid."
        redirect_to edit_camp_path(@camp)
    end

    # if @camp.update(temp_camp_params)
    #   redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was revised in the system."
    # else
    #   render action: 'edit', alert: "Something went wrong."
    # end
  end

  def destroy
    @camp.destroy
    redirect_to camps_url, notice: "#{@camp.name} camp on #{@camp.start_date.strftime('%m/%d/%y')} was removed from the system."
  end

  def report
    @registrations = @camp.registrations
  end

  private
    def set_camp
      @camp = Camp.find(params[:id])
    end

    def camp_params
      params.require(:camp).permit(:curriculum_id, :location_id, :cost, :start_date, :end_date, :time_slot, :max_students, :active, :instructor_ids => [])
    end
end

app/views/camps/_camp_details.html.erb
<h3>Camp Details</h3><br />
<strong>Name:&nbsp;&nbsp;</strong> 
  <% if can? :read, @curriculum %>
    <%= link_to @camp.name, curriculum_path(@curriculum) %><br /><br />
  <% else %>
    <%= @camp.name %><br /><br />
  <% end %>

<strong>Description:&nbsp;&nbsp;</strong> 
  <%= @curriculum.description %><br /><br />

<strong>Cost:&nbsp;&nbsp;</strong> 
  <%= number_to_currency(@camp.cost) %><br /><br />

<strong>Max Students:&nbsp;&nbsp;</strong> 
  <%= @camp.max_students %><br /><br />

<strong>Rating Range:&nbsp;&nbsp;</strong> 
  <%= @curriculum.min_rating.zero? ? "Unrated" : @curriculum.min_rating %> - <%= @curriculum.max_rating %><br /><br />

<strong>Dates:&nbsp;&nbsp;</strong> 
  <%= @camp.start_date.strftime('%m/%d/%y') %> 
  <% if @camp.start_date != @camp.end_date %>
    <%= "- #{@camp.end_date.strftime('%m/%d/%y')}" %>
  <% end %>
  <br /><br />

<strong>Time:&nbsp;&nbsp;</strong> 
  <%= @camp.time_slot == "am" ? "Morning" : "Afternoon" %><br /><br />

<strong>Location:&nbsp;&nbsp;</strong> 
  <% if can? :read, @location %>
    <%= link_to @location.name, location_path(@location) %><br />
  <% else %>
    <%= @location.name %><br />
  <% end %>
  <%= @location.street_1 %>
  <% unless @location.street_2.nil? %>
    <br /><%= @location.street_2 %>
  <% end %>
  <br /><%= @location.city %>, <%= @location.state %> <%= @location.zip %><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= @camp.active ? "Yes" : "No" %><br /><br />

<div id="registered_students">
  <%= render partial: "list_of_registered_students" %>
</div>

<% if logged_in? && (current_user.role? :admin) %>
  <br/><p>
    <%= link_to (camp_report_path(@camp)), class: 'button tiny radius' do %>
        <i class="fa fa-file-text"></i>
        &nbsp;Camp Payment Report
    <% end %>
  </p>
<% end %>

app/views/camps/_camp_instructors.html.erb
<% unless @instructors.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Camp Instructors</h5>
    <ul class="side-nav">
      <% @instructors.each do |instructor| %>
        <li><%= link_to instructor.name, instructor_path(instructor) %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>No Instructors Assigned Yet</h5>
  </div>
<% end %>

app/views/camps/_camps.html.erb
<% unless camps.empty? %>
  <h3><%= status %> Camps</h3>

  <table class="table">
    <tr>
      <th width="200">Name</th>
      <th width="120">Start On</th>
      <th width="120">Time</th>
      <th></th>
      <th></th>
    </tr>

  <% camps.each do |camp| %>
    <tr>
      <td><%= link_to camp.name, camp_path(camp) %></td>
      <td align="center"><%= camp.start_date.strftime('%m/%d/%y') %></td>
      <td align="center"><%= camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
      <% if can? :edit, camp %>
        <td><%= link_to 'Edit', edit_camp_path(camp), class: "button tiny radius" %></td>
      <% end %>
      <% if logged_in? && (current_user.role? :admin) %>
        <td><%= link_to 'Generate Report', camp_report_path(camp), class: "button tiny radius" %></td>
      <% end %>
    </tr>
  <% end %>
  </table>

  <%= render partial: "partials/add_pagination", locals: {objects: camps} %>
<% end %>

app/views/camps/_form.html.erb
<%= simple_form_for(@camp, html: { class: 'form-horizontal' }) do |f| %>
       
    <div class="row">
      <div class="small-6 columns">
        <h3><%= controller.action_name.capitalize %> Camp</h3>
        <%= f.input :curriculum_id, collection: Curriculum.active.alphabetical, prompt: "Select curriculum..." %>
        <%= f.input :cost %>
        <%= f.input :max_students %>
        <%= f.input :start_date, label: "Start Date", as: :string, start_year: Date.today.year - 1, end_year: Date.today.year + 1, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, label: "End Date", as: :string, include_blank: true, start_year: Date.today.year - 1, end_year: Date.today.year + 1, input_html: {class: "datepicker"} %>
        <%= f.input :time_slot, collection: [['Morning','am'],['Afternoon','pm']], prompt: "Select time..." %>
        <%= f.input :location_id, collection: Location.active.alphabetical, prompt: "Select location..." %>
        <%= f.input :active %>
      </div>
      <div class="small-1 columns">&nbsp;</div>
      <div class="small-5 columns">
        <% if controller.action_name=="edit" && @camp.active %>
          <h3>Camp Instructor(s)</h3>
          <%= f.input :instructor_ids, label: "", collection: Instructor.active.alphabetical, as: :check_boxes %>
        <% end %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of camps', camps_path, class: 'button secondary radius' %>
    </div>

<% end %>

app/views/camps/_inactive_camps.html.erb
<% if logged_in? && (current_user.role? :admin) %>
	<%= render partial: "partials/inactive_objects", locals: {model_name: "camp", objects: @inactive_camps}  %>
<% end %>

app/views/camps/_list_of_registered_students.html.erb
<% unless @registered_students.empty? %>
  <div>
    <strong>Registrations (<%= @registered_students.size %>)
    </strong>

    <% if logged_in? %>
      <table class="table">
        <th>Student Name</th>
        <th>Rating</th>
        <% if current_user.role? :admin %>
          <th>Payment Status</th>
        <% end %>
        <th>Points Earned</th>
        <th></th>

        <% @registrations.each do |registration| %>
        <tr>
          <td align="center">
            <% if can? :show, registration.student %>

              <%= link_to registration.student.proper_name, student_path(registration.student) %>
            <% else %>
              <%= registration.student.proper_name %>
            <% end %>
          </td>
          <td><%= registration.student.rating %></td>
          <% if current_user.role? :admin %>
            <td align="center">
              <% if registration.payment_status == "deposit" %> 
                <%= link_to edit_student_path(id: registration.id, status: "paid", from: "camp") do %>
                  <%= image_tag 'checkmark_empty.png', class: 'checkmark' %>
                <% end %>
              <% else %>
                <%= image_tag "checkmark_filled.png", class: "checkmark" %>
              <% end %>
            </td> 
          <% end %>
          <td align="center"><%= registration.points_earned %></td>
          <% if can? :edit, registration.student %>
            <td><%= link_to 'Edit', edit_student_path(registration.student), class: "button tiny radius" %></td>
          <% end %>
        </tr>
        <% end %>
      </table>
    <% else %>
      <ul>
        <% @registered_students.each do |student| %>
          <li><%= student.name + " (" + student.age.to_s + ")" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% else %>
  <p>No registered students yet.</p>
<% end %>

app/views/camps/_sidebar.html.erb
<div>
  <%= render partial: "camp_instructors" %>
</div>

<div class="panel clearfix", id="map">
  <h5>Map</h5>
  <%= render partial: "partials/map", locals: {latitude: @location.latitude, longitude: @location.longitude, name: @location.name} %>
</div>

app/views/camps/edit.html.erb
<%= render partial: "partials/display_form", locals: {small: false} %>

app/views/camps/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "camp", 
                                                         primary: "camps", 
                                                         primary_locals: {status: "Upcoming", camps: @upcoming_camps},
                                                         secondary: "camps", 
                                                         secondary_locals: {status: "Past", camps: @past_camps},
                                                         sidebar: "inactive_camps"} %>

app/views/camps/new.html.erb
<%= render partial: "partials/display_form", locals: {small: false} %>

app/views/camps/report.html.erb
<h2>Payment Report for Camp #<%= @camp.id %></h2>

<%= render partial: "partials/single_camp_report", locals: {camp: @camp} %>

app/views/camps/show.html.erb
<%= render partial: "partials/show_structure", locals: {primary: "camp_details",
														primary_locals: nil,
                                                        sidebar: "sidebar"} %>

<div class="options">
	<% if @camp.registrations.size.zero? %>
		<%= render partial: "partials/object_options", locals: {model_name: "camp", object: @camp, can_destroy: true} %>
	<% else %>
		<%= render partial: "partials/object_options", locals: {model_name: "camp", object: @camp, can_destroy: false} %>
	<% end %>
</div>