config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :locations
  resources :students
  resources :families

  resources :users, only: [:create, :destroy]
  resources :sessions

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  get 'login', to: 'home#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # get '*a', to: 'errors#routing'

  get 'camp_report/:id', to: 'camps#report', as: :camp_report
  get 'family_report/:id/', to: 'families#report', as: :family_report
  get 'family_report/:id/:year', to: 'families#yearly_report', as: :family_yearly_report

  get 'annual_report/:year/', to: 'home#annual_report', as: :annual_report
end

app/models/family.rb
class Family < ActiveRecord::Base
  include ChessCampHelpers

  # relationships
  has_many :students
  has_many :registrations, through: :students
  accepts_nested_attributes_for :students, reject_if: lambda { |student| student[:last_name].blank? || student[:first_name].blank? }, allow_destroy: true
  

  # scopes
  scope :alphabetical, -> { order('family_name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  # validations
  validates_presence_of :family_name, :phone
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"

  # callbacks
  before_destroy :is_never_destroyable
  before_save :reformat_phone

  def make_inactive
    self.active = false
    self.save!
  end
  
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController 
	include ActionView::Helpers::NumberHelper
	authorize_resource
	before_action :set_family, only: [:show, :edit, :update, :destroy, :report, :yearly_report]

	def index
		@active_families = Family.active.alphabetical.paginate(page: params[:page]).per_page(10)
		@inactive_families = Family.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
	end

	def show
		@children = @family.students.to_a
	end

	def new
		@family = Family.new
		@family.students.build
	end

	def edit
		@family.phone = number_to_phone(@family.phone)
		@family.students.build if @family.students.nil?
		@family.students.each do |student|
			student.date_of_birth = humanize_date student.date_of_birth
		end

	end

	def create
		params[:family][:students_attributes].values.each do |student|
		  student[:date_of_birth] = Chronic.parse(student[:date_of_birth])
		end if params[:family] and params[:family][:students_attributes]

		puts params[:family][:students_attributes]

		@family = Family.new(family_params)
		if @family.save
			redirect_to @family, notice: "#{@family.family_name} family was added to the system."
		else
			#@family.students.build
			render action: 'new'
		end
	end

	def update
		params[:family][:students_attributes].values.each do |student|
		  student[:date_of_birth] = Chronic.parse(student[:date_of_birth])
		end if params[:family] and params[:family][:students_attributes]

		if @family.update(family_params)
			redirect_to @family, notice: "#{@family.family_name} family was revised in the system."
		else
			render action: 'edit'
		end
	end

	def destroy
		@family.destroy
		redirect_to families_url, notice: "#{@family.family_name} was removed from the system."
	end

	def report
	    @registrations = @family.students.map{|s| s.registrations}.flatten.to_a
	    @camps = @family.students.map{|s| s.camps}.flatten.to_a
	    @years = @camps.map{|c| c.start_date.year}.uniq
	end

	def yearly_report
		@year = params[:year]
		@registrations = @family.students.map{|s| s.registrations}.flatten.to_a
		@registrations_in_year = @registrations.map { |r| r if r.camp.start_date.to_date.year == @year.to_i}.to_a
	end

	private
	def set_family
		@family = Family.find(params[:id])
	end

	def family_params
		params.require(:family).permit(:family_name, :parent_first_name, :email, :phone, :active, students_attributes: [:id, :first_name, :last_name, :rating, :date_of_birth, :active, :_destroy])
	end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_active_families.html.erb
<h3>Active Families</h3>

<table class="table">
  <tr>
    <th width="150">Family Name</th>
    <th width="100">Parent</th>
    <th width="200">Phone</th>
    <th></th>
    <th></th>
  </tr>

<% @active_families.each do |family| %>
  <tr>
    <td align="center"><%= link_to family.family_name, family_path(family) %></td>
    <td align="center"><%= family.parent_first_name %></td>
    <td align="center"><%= number_to_phone family.phone %></td>
    <td><%= link_to 'Edit', edit_family_path(family), class: "button tiny radius" %></td>
    <td>
      <% if current_user.role? :admin %>
        <%= link_to (family_report_path(family)), class: 'button tiny radius' do %>
            Generate Report
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<%= render partial: "partials/add_pagination", locals: {objects: @active_families} %>

app/views/families/_children_information.html.erb
<% unless @children.empty? %>
  <div class="panel clearfix">
    <h5>Children</h5>
    <ul class="side-nav">
      <% @children.each do |child| %>
        <li><%= link_to child.proper_name, eval("student_path(child)") %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/families/_family_details.html.erb
<h3>Family Details</h3><br />
<strong>Family Name:&nbsp;&nbsp;</strong> 
  <%= @family.family_name %> <br /><br />

<strong>Parent First Name:&nbsp;&nbsp;</strong> 
  <%= @family.parent_first_name %><br /><br />

<strong>Phone:&nbsp;&nbsp;</strong> 
  <%= number_to_phone(@family.phone) %><br /><br />

<strong>Email:&nbsp;&nbsp;</strong> 
  <%= mail_to @family.email, @family.email, encode: "javascript" %><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= @family.active ? "Yes" : "No" %><br /><br />

<% if current_user.role? :admin %>
  <br/><p>
    <%= link_to (family_report_path(@family)), class: 'button tiny radius' do %>
        <i class="fa fa-file-text"></i>
        &nbsp;Family Payment Report
    <% end %>
  </p>
<% end %>

<%= render partial: "partials/object_options", locals: {model_name: "family", object: @family, can_destroy: false} %>

app/views/families/_family_fields.html.erb
<%= f.input :family_name %>
<%= f.input :parent_first_name %>
<%= f.input :phone, as: :string %>
<%= f.input :email %>
<%= f.input :active %>

app/views/families/_form.html.erb
<%= simple_nested_form_for(@family, html: { class: 'form-horizontal' }) do |family_form| %>
   <div class="row"> 
     <div class="small-6 columns">
       <h3><%= controller.action_name.capitalize %> Family</h3>
       <%= render partial: "family_fields", locals: { f: family_form } %>
       

       <div class="form-actions">
         <%= family_form.submit nil, class: 'button radius' %>
         <%= link_to 'Back to list of families', families_path, class:  'button secondary radius' %>
       </div>
     </div>

     <div class="small-1 columns">&nbsp;</div>
      
     <div class="small-5 columns">
       <% if controller.action_name == "edit" %>
         <%= family_form.simple_fields_for :students do |student_form| %>
            <%= render partial: "student_fields", locals: { f: student_form } %>
         <% end %>
         <%= family_form.link_to_add("Add Student", :students, class: 'button tiny') %>
        <% end %>
     </div>
   </div>
    
<% end %>

app/views/families/_inactive_families.html.erb
<%= render partial: "partials/inactive_objects", locals: {model_name: "family", objects: @inactive_families}  %>

app/views/families/_student_fields.html.erb
<div class="fields">
	<div class="dynamic_add">
	  <%= f.link_to_remove do %>
	  	<i class="fa fa-times-circle fa-lg close_button"></i>
	  <% end %>

	  <h4>Add a Student</h4>
	  <!-- fields -->
	  <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :date_of_birth, as: :string, label: "Date of Birth", input_html: {class: "datepicker"} %> 
      <%= f.input :rating %>
      <%= f.input :active %>
	</div>
</div>

app/views/families/edit.html.erb
<%= render partial: "partials/display_form", locals:{small: false} %>

app/views/families/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "family", 
                                                         primary: "active_families",
                                                         primary_locals: nil, 
                                                         secondary: nil, 
                                                         secondary_locals: nil,
                                                         sidebar: "inactive_families"} %>

app/views/families/new.html.erb
<%= render partial: "partials/display_form", locals:{small: false} %>

app/views/families/report.html.erb
<h2>Payment Report for <%= @family.family_name %> Family</h2>

<% unless @years.empty? %>
	<p>Select a year:</p>
	<% @years.each do |y| %>
		<%= link_to (family_yearly_report_path(@family, y)), class: 'button tiny radius' do %>
	        &nbsp;<%= y %>
	    <% end %><br /><br />
	<% end %>
<% else %>
	<p>Family has no registrations.</p>
<% end %>

app/views/families/show.html.erb
<%= render partial: "partials/show_structure", locals: {primary: "family_details",
														primary_locals: nil, 
                                                        sidebar: "children_information"} %>

app/views/families/yearly_report.html.erb
<h2>Report for <%= @family.family_name %> Family in <%= @year %></h2>

<table>
	<thead>
		<th width="200">Student Name</th>
		<th width="250">Camp</th>
		<th width="170">Payment Recieved</th>
		<th width="170">Balance Due</th>
	</thead>
	<tbody>
		<% total_paid = 0 %>
		<% amount_due = 0 %>
		<% @registrations_in_year.each do |registration| %>
		<tr>
			<td><%= link_to registration.student.proper_name, student_path(registration.student) %></td>
			
			<% camp = registration.camp %>

			<td><%= link_to "#{camp.name + " (" + camp.start_date.strftime('%m/%d/%y') + ")"}", camp_path(camp) %></td>
			
			<% if registration.payment_status == 'deposit' %>
				<% total_paid += 50 %>
				<% amount_due += camp.cost - 50 %>
				<td align="center"><%= number_to_currency(50) %></td>
				<td align="center"><%= number_to_currency(camp.cost - 50) %></td>
			<% else %>
				<% total_paid += camp.cost %>
				<td align="center"><%= number_to_currency(camp.cost) %></td>
				<td align="center"><%= number_to_currency(0) %></td>
			<% end %>
		</tr>
		<% end %>
		<tr>
			<td><strong>Total</strong></td>
			<td></td>
			<td align="center"><strong><%= number_to_currency(total_paid) %></strong></td>
			<td align="center"><strong><%= number_to_currency(amount_due) %></strong></td>
		</tr>
	</tbody>

</table>