config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :locations
  resources :students
  resources :families

  resources :users, only: [:create, :destroy]
  resources :sessions

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  get 'login', to: 'home#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # get '*a', to: 'errors#routing'

  get 'camp_report/:id', to: 'camps#report', as: :camp_report
  get 'family_report/:id/', to: 'families#report', as: :family_report
  get 'family_report/:id/:year', to: 'families#yearly_report', as: :family_yearly_report

  get 'annual_report/:year/', to: 'home#annual_report', as: :annual_report
end

app/views/partials/_add_pagination.html.erb
<span class="paginate">
	<% if defined?(name).nil?%>
		<% name = "page"%> 
	<% end %>
	<%= will_paginate objects, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next", param_name: name %>
	<br />
</span>

app/views/partials/_display_form.html.erb
<div class="row">
  <% if small == true %>
  	<div class="small-8 columns">
  <% else %>
    <div class="small-12 columns">
  <% end %>
	  <%= render partial: "form" %>
	</div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert class="alert-box <%= :notice ? "success" : "warning" %> radius">
    <a href="#" class="close">&times;</a>
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
<%= link_to 'About Us', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
<%= link_to 'Privacy Policy', privacy_path %>
<br /><br />
<div id="copy">
	Webmaster: <%= mail_to("sherryc1@andrew.cmu.edu", "Sherry Chen", encode: "javascript") %> 
	&nbsp;&nbsp;&copy 2014
</div>

app/views/partials/_inactive_objects.html.erb
<% unless objects.empty? %>
  <div class="panel clearfix">
    <h5>Inactive <%="#{model_name.pluralize.capitalize}" %>
    </h5>
    <ul class="side-nav">
      <% objects.each do |object| %>
        <li><%= link_to object.name, eval("#{model_name}_path(object)") %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns">
    <% if primary_locals.nil? %>
      <%= render partial: "#{primary}" %>
    <% else %>
      <%= render partial: "#{primary}", locals: primary_locals %>
    <% end %>
    
    <% unless secondary.nil? && secondary_locals.nil? %>
      <% if secondary_locals.nil? %>
        <%= render partial: "#{secondary}" %>
      <% else %>
        <%= render partial: "#{secondary}", locals: secondary_locals %>
      <% end %>
    <% end %>
  </div>

  <div class="small-4 columns">
    <%= render partial: "#{sidebar}" unless sidebar.nil? %>
  </div>
</div>

<% if can? :add, eval(":#{model_name}") %>
  <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
    <i class="fa fa-plus"></i>
    &nbsp;Add a New <%= model_name.capitalize %>
  <% end %>
<% end %>

app/views/partials/_map.html.erb
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyChdkxc1wKfZt92uBvQabkYTS8hmqJsbz8&sensor=false">
</script>
<script type="text/javascript">
  function initialize() {
    var myLatlng = new google.maps.LatLng(<%= latitude %>, <%= longitude %>);
    var mapOptions = {
      center: myLatlng,
      zoom: 16
    };
    var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: "<%= name %>"
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

<style type="text/css">
  #map-canvas { height: 250px; }
</style>

<div id="map-canvas"/>

app/views/partials/_nav.html.erb
  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name" id="logo">
          <%= link_to image_tag('amcc_logo.png'), home_path %>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <% if logged_in? && (current_user.role? :admin) %>
              <%= render partial: "partials/nav_item", locals: {model_name: "curriculum"} %>
              <%= render partial: "partials/nav_item", locals: {model_name: "camp"} %>
              <%= render partial: "partials/nav_item", locals: {model_name: "location"} %>
              <%= render partial: "partials/nav_item", locals: {model_name: "instructor"} %>
              <%= render partial: "partials/nav_item", locals: {model_name: "family"} %>
              <%= render partial: "partials/nav_item", locals: {model_name: "student"} %>
          <% else %>
            <li><%= link_to "List Camps", camps_path %></li>
          <% end %>
        </ul>
       </section>
       
       <section class="top-bar-section"> 
          <div id="container" class="right">
            <div id="login">
              <% if logged_in? %>
                <div id="nav_right"><%= current_user.instructor.proper_name %> : <%= link_to 'Logout', logout_path %></div>

              <% else %>

                <%= form_tag sessions_path do %>
                  <form>
                    <div class="login_f"><%= text_field_tag :username, nil, placeholder: "username", id:"username" %></div>
                    <div class="login_f"><%= password_field_tag :password, nil, placeholder: "password", id:"password" %></div>
                    <%= submit_tag "Log In", id:"login" %>
                  </form>
                <% end %>
              
              <% end %>
            </div>
          </div>
        </ul>
      </section>
    </nav>
  </div>

app/views/partials/_nav_item.html.erb
<li class="has-dropdown">
  <%= link_to "#{model_name.capitalize.pluralize}", eval("#{model_name.pluralize}_path") %>
  <ul class="dropdown">
    <li><%= link_to "List #{model_name.capitalize.pluralize}", eval("#{model_name.pluralize}_path") %></li>
    <li><%= link_to "Add a #{model_name.capitalize}", eval("new_#{model_name}_path") %></li>
  </ul>
</li>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  
  <% if can? :index, eval(":#{model_name}") %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'button tiny radius') do %>
      <i class="fa fa-list"></i>
      &nbsp;Display All <%= model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>

  <% if (can? :edit, eval(":#{model_name}")) || (can? :edit, @instructor) %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button tiny radius') do %>
      <i class="fa fa-pencil"></i>
      &nbsp;<%= "Update #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>

  <% if can? :destroy, eval(":#{model_name}") %>
    <% if can_destroy %>
      <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button tiny radius alert') do %>
        <i class="fa fa-trash-o"></i>
        &nbsp;<%= "Delete #{opt}" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/partials/_show_structure.html.erb
<!-- This one includes a 1-column space between main and sidebar -->
<div class="row">
  <div class="small-7 columns">
    <% if primary_locals.nil? %>
      <%= render partial: "#{primary}" %>
    <% else %>
      <%= render partial: "#{primary}", locals: primary_locals %>
    <% end %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <%= render partial: "#{sidebar}" unless sidebar.nil? %>
  </div>
</div>

app/views/partials/_single_camp_report.html.erb
<em>Name:&nbsp;&nbsp;</em><%=camp.name %>, 
<em>Dates:&nbsp;&nbsp;</em> 
<%= camp.start_date.strftime('%m/%d/%y') %> 
<% if camp.start_date != camp.end_date %>
<%= "- #{camp.end_date.strftime('%m/%d/%y')}" %>
<% end %>, 
<em>Time:&nbsp;&nbsp;</em> 
<%= camp.time_slot == "am" ? "Morning" : "Afternoon" %><br /><br />

<table>
	<thead>
		<th width="180">Student Name</th>
		<th width="170">Payment Recieved</th>
		<th width="170">Amount Due</th>
	</thead>
	<tbody>
		<% @total_paid = 0 %>
		<% @amount_due = 0 %>
		<% camp.registrations.each do |registration| %>
		<tr>
			<td><%= link_to registration.student.proper_name, student_path(registration.student) %></td>

			<% if registration.payment_status == 'deposit' %>
				<% @total_paid += 50 %>
				<% @amount_due += camp.cost - 50 %>
				<td align="center"><%= number_to_currency(50) %></td>
				<td align="center"><%= number_to_currency(camp.cost - 50) %></td>
			<% else %>
				<% @total_paid += camp.cost %>
				<td align="center"><%= number_to_currency(camp.cost) %></td>
				<td align="center"><%= number_to_currency(0) %></td>
			<% end %>
		</tr>
		<% end %>
		<tr>
			<td><strong>Total</strong></td>
			<td align="center"><strong><%= number_to_currency(@total_paid) %></strong></td>
			<td align="center"><strong><%= number_to_currency(@amount_due) %></strong></td>
		</tr>
	</tbody>
</table>