config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :locations
  resources :students
  resources :families

  resources :users, only: [:create, :destroy]
  resources :sessions

  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  get 'login', to: 'home#index', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # get '*a', to: 'errors#routing'

  get 'camp_report/:id', to: 'camps#report', as: :camp_report
  get 'family_report/:id/', to: 'families#report', as: :family_report
  get 'family_report/:id/:year', to: 'families#yearly_report', as: :family_yearly_report

  get 'annual_report/:year/', to: 'home#annual_report', as: :annual_report
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	@upcoming_camps = Camp.active.upcoming.chronological.paginate(page: params[:ucpage]).per_page(10)
    if logged_in? 
      @instructor = current_user.instructor
      @assigned_camps = @current_user.instructor.camps.upcoming.chronological.paginate(page: params[:acpage]).per_page(10)
      if current_user.role? :admin
  		  @families = Family.alphabetical.paginate(page: params[:fpage]).per_page(10)
        @years = Camp.active.map{|c| c.start_date.year}.uniq
        @instructors = Instructor.active.alphabetical.paginate(page: params[:ipage]).per_page(10)
      end
  	end
  end

  def about
  end

  def contact
  end

  def privacy
  end
  
  def annual_report
    @year = params[:year]
    @camps_in_year = Camp.active.chronological.map{|c| c if c.start_date.to_date.year == @year.to_i}.compact.to_a
    @registrations_deposit_only = @camps_in_year.map{|c| c.registrations.deposit_only}.flatten.to_a
    @students = @registrations_deposit_only.map{ |r| r.student }.uniq.sort! { |a,b| a.name <=> b.name }.to_a

  end

end

app/views/home/_admin.html.erb
<div class="row">
	<dl class="tabs" data-tab >
	  <dd class="active"><%= link_to "Upcoming Camps", home_path(anchor: "admin-1") %></dd>
	  <dd><%= link_to "Families", home_path(anchor: "admin-2") %></dd>
	  <dd><%= link_to "Instructors", home_path(anchor: "admin-3") %></dd>
	  <dd><%= link_to "Annual Camp Reports", home_path(anchor: "admin-4") %></dd>
	  <dd><%= link_to "My Camps", home_path(anchor: "admin-5") %></dd>
	  <dd><%= link_to "My Profile", home_path(anchor: "admin-6") %></dd>
	</dl>
	<div class="tabs-content">
	  <div class="content active" id="admin-1">
	    <%= render partial: "tab_camps", locals: {camps: @upcoming_camps} %>
	  </div>
	  <div class="content" id="admin-2">
	    <%= render partial: "tab_families" %>
	  </div>
	  <div class="content" id="admin-3">
	  	<%= render partial: "tab_instructors" %>
	  </div>
	  <div class="content" id="admin-4">
	    <%= render partial: "annual_camp_reports" %>
	  </div>
	  <div class="content" id="admin-5">
	    <%= render partial: "camps_instructing" %>
	  </div>
	  <div class="content" id="admin-6">
	    <%= render partial: "instructor_profile" %>
	  </div>
	</div>
</div>

app/views/home/_annual_camp_reports.html.erb
<% unless @years.empty? %>
	<h4>Select a Year to Generate a Report For:</h4>
	<% @years.each do |y| %>
		<%= link_to annual_report_path(y), class: 'button radius' do %>
	        &nbsp;<%= y %>
	    <% end %><br /><br />
	<% end %>
<% else %>
	<p>There are no annual reports.</p>
<% end %>

app/views/home/_camps_instructing.html.erb
<h3>Upcoming Assigned Camps</h3>
<table>
  <tr>
    <th width="200">Name</th>
    <th width="120">Start On</th>
    <th width="120">Time</th>
    <th></th>
    <th></th>
  </tr>

<% @assigned_camps.each do |camp| %>
  <tr>
    <td><%= link_to camp.name, camp_path(camp) %></td>
    <td align="center"><%= camp.start_date.strftime('%m/%d/%y') %></td>
    <td align="center"><%= camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
    <% if can? :edit, camp %>
      <td><%= link_to 'Edit', edit_camp_path(camp), class: "button tiny radius" %></td>
    <% end %>
  </tr>
<% end %>
</table>

<%= render partial: "partials/add_pagination", locals: {objects: @assigned_camps, name: "acpage" } %>

app/views/home/_family_admin_details.html.erb
<h4><%= family.family_name %> Family</h4>
<strong>Contact:&nbsp;&nbsp;</strong> 
  <%= family.parent_first_name + " " + family.family_name %><br /><br />

<strong>Phone:&nbsp;&nbsp;</strong> 
  <%= number_to_phone(family.phone) %><br /><br />

<strong>Email:&nbsp;&nbsp;</strong> 
  <%= mail_to family.email, family.email, encode: "javascript" %><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= family.active ? "Yes" : "No" %><br /><br />


<strong>Annual Reports:&nbsp;&nbsp;</strong>
<% @fyears = family.students.map{ |s| s.camps}.flatten.to_a.map{|c| c.start_date.year}.uniq %>

<% unless @fyears.empty? %>
	<p>Select a year:</p>
	<% @fyears.each do |y| %>
		<%= link_to (family_yearly_report_path(family, y)), class: 'button small radius' do %>
	        &nbsp;<%= y %>
	    <% end %><br /><br />
	<% end %>
<% else %>
	<p>Family has no registrations yet.</p>
<% end %>

app/views/home/_guest.html.erb
<div class="row"> 
 <div class="small-7 columns">
   <h2>Welcome to Alex and Mark Chess Camps!</h2>
   <p>Chess camp is typically a week long, three hours a day intense training in a specific area of chess. Difficulty levels range from principles to much more advanced tactics such as Nimzo-Indian Defense. Morning sessions are held from <strong> 9:00am - 12:00pm </strong> while afternoon sessions are held from <strong> 1:00pm - 4:00pm </strong>.</p>
   <p>We guarantee you a 1:4 instructor to student ratio because we know that is the most effective. The primary instructors for this summer will be Alex and Mark Heimann, who have jointly won eight national scholastic chess championships. Mark is currently among the top 100 players in the United States (USCF rating: 2449), while Alex has earned his Life Master title with a current USCF rating of 2374.</p>
   <p><strong>Unfortunately, at this time, registration for camps cannot be completed online. </strong>Therefore, if you are ready to enroll your student in a specific camp, feel free to reach out to the administrator: <%= link_to "Professor Heimann", contact_path %>. </p>
 </div>

 <div class="small-1 columns">&nbsp;</div>
  
 <div class="small-4 columns">
   <%= render partial: "list_upcoming_camps" %>
   
 </div>
</div>

app/views/home/_instructor.html.erb
<div class="row">
	<div class="small-6 columns">
		<div><%=render partial: "camps_instructing" %></div>
	</div>

	<div class="small-6 columns">
		<%= render partial: "instructor_profile" %>
	</div>
</div>

app/views/home/_instructor_profile.html.erb
<div class="instructor_profile">
	<%= render partial: "instructors/instructor_details", locals: {only_edit: true} %>
	<%= link_to "Edit Profile", edit_instructor_path(@instructor), class: 'button tiny radius' %>
</div>

app/views/home/_list_upcoming_camps.html.erb
<% unless @upcoming_camps.empty? %>
  <div class="panel clearfix">
    <h4>Upcoming Camps</h4>
    <ul class="side-nav">
      <% @upcoming_camps.each do |camp| %>
        <li><%= link_to "#{camp.name + ': ' + camp.start_date.strftime('%m/%d/%y') + " (" + camp.time_slot+")"}", camp_path(camp) %></li>
      <% end %>
      <%= render partial: "partials/add_pagination", locals: {objects: @upcoming_camps} %>
    </ul>
  </div>

<% else %>
	<p>No upcoming assigned camps yet.</p>
<% end %>

app/views/home/_tab_camps.html.erb
<dl class="tabs vertical" data-tab>
  <% i = 1 %>
  <% camps.each do |camp| %>
  	<% if i == 1 %>
  		<dd class="active"><a href="#camp1a">
        <%= camp.name %> :: <%= camp.start_date.strftime('%m/%d/%y') %>
        <% if camp.registrations.size < 3 || camp.instructors.size.zero? || camp.registrations.size.to_i/camp.instructors.size.to_i > 4 %>
          <i class="fa fa-exclamation-triangle fa-lg"></i>
        <% end %>
      </a></dd>
  	<% else %>
  		<dd><a href="#camp<%= i.to_s %>a">
        <%= camp.name %> :: <%= camp.start_date.strftime('%m/%d/%y') %>
        <% if camp.registrations.size < 3 || camp.instructors.size.zero? || camp.registrations.size.to_i/camp.instructors.size.to_i > 4 %>
          <i class="fa fa-exclamation-triangle fa-lg"></i>
        <% end %>
      </a></dd>
  	<% end %>
  	<% i=i+1 %>
  <% end %>
  <div class="vertical_tabs_pagination"> <%= render partial: "partials/add_pagination", locals: {objects: camps, name: "ucpage" } %></div>

</dl>

<div class="tabs-content vertical">
  <% i = 1 %>
  <% camps.each do |camp| %>
  	<% if i == 1 %>
  		<div class="content active" id="camp1a">
  	<% else %>
		<div class="content" id="camp<%=i.to_s %>a" >
  	<% end %>
		  <%= render partial: "camp_admin_details", locals: {camp: camp} %>
		</div>
  	<% i = i + 1 %>
  <% end %>
</div>

app/views/home/_tab_instructors.html.erb
<dl class="tabs vertical" data-tab>
  <% i = 1 %>
  <% @instructors.each do |instructor| %>
  	<% if i == 1 %>
  		<dd class="active"><a href="#instructor1a">
        <%= instructor.name %>
        <% if instructor.camps.size.zero? || instructor.camps.size > 10 %>
          <i class="fa fa-exclamation-triangle fa-lg"></i>
        <% end %>
      </a></dd>
  	<% else %>
  		<dd><a href="#instructor<%= i.to_s %>a">
        <%= instructor.name %>
        <% if instructor.camps.size < 2 || instructor.camps.size > 10 %>
          <i class="fa fa-exclamation-triangle fa-lg"></i>
        <% end %>
      </a></dd>
  	<% end %>
  	<% i=i+1 %>
  <% end %>
  <div class="vertical_tabs_pagination"> <%= render partial: "partials/add_pagination", locals: {objects: @instructors, name: "ipage" } %></div>

</dl>

<div class="tabs-content vertical">
  <% i = 1 %>
  <% @instructors.each do |instructor| %>
  	<% if i == 1 %>
  		<div class="content active" id="instructor1a">
  	<% else %>
		<div class="content" id="instructor<%=i.to_s %>a" >
  	<% end %>
		  <%= render partial: "instructor_admin_details", locals: {instructor: instructor} %>
		</div>
  	<% i = i + 1 %>
  <% end %>
</div>

app/views/home/about.html.erb
<div class="row">
	<div class="small-7 columns">
		<h2>About the A &amp; M Chess Camps</h2>

		<p> 
		  To reiterate what is said on the home page, Alex and Mark Heimann are two very talented chess players, who are looking this summer to share this knowledge with excited students looking to get into chess or further their study. Every camp, regardless of difficulty, is guaranteed to have a 1:4 instructor to student ratio. To look at some of the upcoming camps, click <%= link_to "here", camps_path %>.
		</p>
	</div>
	<div class="small-1 columns">&nbsp;</div>

	<div class="small-4 columns">
		<%= image_tag 'Luke&Erik2.jpg' %>
	</div>
</div>

app/views/home/annual_report.html.erb
<div class="row">
	<div class="small-7 columns" >
		<h2 id="top">Annual Camp Payment Report for <%= @year %></h2>
		<% @annual_paid = 0 %>
		<% @annual_due = 0 %>

		<% @camps_in_year.each do |c| %>
			<div>
				<%= render partial: "partials/single_camp_report", locals: {camp: c} %>
				<% @annual_paid+= @total_paid %>
				<% @annual_due += @amount_due %>
			</div>
		<% end %>
		<a href="#top" class="button radius">Back to Top</a>
	</div>
	<div class="small-1 columns"> 
		&nbsp;
	</div>

	<div class="small-4 columns panel clearfix">
		<h3>Summary</h3>
		<strong>Total Payments Recieved: </strong>
		<%= number_to_currency(@annual_paid) %><br /><br />
		<strong>Total Balances Due: </strong>
		<%= number_to_currency(@annual_due) %><br /><br />
		<em>Students with Outstanding Balances:</em><br/><br />
		<ul>
			<% @students.each do |student| %>
				<li><%= link_to student.name, student_path(student) %></li>
			<% end %>
		</ul>
	</div>
</div>

app/views/home/index.html.erb
<% if logged_in? %> 
	<% if current_user.role?(:instructor) %>
		<%= render partial: "instructor" %>
	<% else %>
		<%= render partial: "admin" %>
	<% end %>
<% else %>
	<%= render partial: "guest" %>
<% end %>

app/views/home/privacy.html.erb
<div class="row" >
	<div class="small-4 columns">
		<%= image_tag 'SamPlaying.jpg' %>
	</div>
	
	<div class="small-1 columns">&nbsp;</div>

	<div class="small-7 columns" >
		<h2>The A &amp;M Chess Camp Privacy Policy</h2>

		<em>Parents:</em>
		<p>There are no cookies on our website, and purchases cannot be made online anyway. Therefore, all transactions must be made over the phone or in person. We only take cash or check, and do not accept any type of credit or debit card. Therefore you do not need to worry about any financial security risk because we have none. 
		</p>

		<p>Do note that, with expressed consent, we are free to use pictures of your child in the form of advertisement for our service. Furthermore, their name and age will appear under all camps they are registered for in order to better aid other parents in understanding what type of camp they might consider registering their child for.</p>

		<em>Instructors:</em>
		<p>Your contact information is neither physically available to the public nor to other instructors, aside from administrators. We are free to change this, however we will notify you when we are officially making this switch.</p>

	</div>
</div>